// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nVIbqDdTe1o0Gql0lrkdFq9lHLYWQ6E',
    appId: '1:517214893199:web:723012af5df98bdca26cfa',
    messagingSenderId: '517214893199',
    projectId: 'daily-sales-record-5d41b',
    authDomain: 'daily-sales-record-5d41b.firebaseapp.com',
    storageBucket: 'daily-sales-record-5d41b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSpfT5fGttO1661PL1A1o8By5OGFDpxs',
    appId: '1:517214893199:android:55a11f587be40625a26cfa',
    messagingSenderId: '517214893199',
    projectId: 'daily-sales-record-5d41b',
    storageBucket: 'daily-sales-record-5d41b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Y-ghB2Vc5wtX1tGyhwJwRBd-UwfZqdI',
    appId: '1:517214893199:ios:8209fc0fd34248c1a26cfa',
    messagingSenderId: '517214893199',
    projectId: 'daily-sales-record-5d41b',
    storageBucket: 'daily-sales-record-5d41b.firebasestorage.app',
    iosBundleId: 'com.antigravity.deliverypro.stitchDailyDeliveryLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nVIbqDdTe1o0Gql0lrkdFq9lHLYWQ6E',
    appId: '1:517214893199:web:a38b43b91ef53424a26cfa',
    messagingSenderId: '517214893199',
    projectId: 'daily-sales-record-5d41b',
    authDomain: 'daily-sales-record-5d41b.firebaseapp.com',
    storageBucket: 'daily-sales-record-5d41b.firebasestorage.app',
  );
}

